
services:
  mysql:
    image: mysql
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABSE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD={DB_PASSWORD}
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      - PMA_HOST=${PMA_HOST}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql
